name: Deployment and Jenkins run
on:
  push:
    branches:
      - dev
      - pipeline-rework
  pull_request:
    branches:
      - master
jobs:
  deploy_test:
    runs-on: ubuntu-latest
    name: deploy-test
    env:
      SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      SERVER_ADDR: ${{ secrets.SERVER_ADDR }}
      SSH_USER: ${{ secrets.SSH_USER }}
    steps:
      - run: |
          command -v ssh-agent >/dev/null || ( apt install ssh )
          eval `ssh-agent -s` && echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add - 
          mkdir -p ~/.ssh && chmod 700 ~/.ssh 
          echo -e "Host *\n\tStrictHostKeyChecking no\n\tPort 2223\n\n" > ~/.ssh/config
          ssh $SSH_USER@$SERVER_ADDR "./deploy_django.sh"
  run_jenkins:
    name: Jenkins pipeline
    runs-on: ubuntu-latest
    steps:
      - name: Jenkins job
        uses: appleboy/jenkins-action@master
        with:
          url: "https://38600.ddns.net:9002"
          user: "paloudi"
          token: ${{ secrets.JENKINS_TOKEN }}
          job: "projet-cicl"
