name: Deployment and Jenkins run
on:
  push:
    branches:
      - dev
      - pipeline-rework
  pull_request:
    branches:
      - master
      - dev
jobs:
  deploy_test:
    runs-on: ubuntu-latest
    name: deploy-test
    env:
      SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      SERVER_ADDR: ${{ secrets.SERVER_ADDR }}
      SSH_USER: ${{ secrets.SSH_USER }}
    steps:
      - run: command -v ssh-agent >/dev/null || ( apt install ssh )
      - run: eval `ssh-agent -s` && echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add - 
      - run: mkdir -p ~/.ssh && chmod 700 ~/.ssh 
      - run: echo -e "Host *\n\tStrictHostKeyChecking no\n\tPort 2223\n\n" > ~/.ssh/config
      - run: ssh $SSH_USER@$SERVER_ADDR "hostname && echo 'Welcome!!!' > welcome.txt"
