name: Deployment and Jenkins run
on:
  push:
    branches:
      - dev
      - pipeline-rework
  pull_request:
    branches:
      - master
      - dev
jobs:
  deploy_test:
    runs-on: ubuntu-latest
    name: deploy-test
    env:
      SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      SERVER_ADDR: ${{ secrets.SERVER_ADDR }}
      SSH_USER: ${{ secrets.SSH_USER }}
    steps:
      - run: |
          command -v ssh-agent >/dev/null || ( apt install ssh )
          eval `ssh-agent -s` && echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add - 
          mkdir -p ~/.ssh && chmod 700 ~/.ssh 
          echo -e "Host *\n\tStrictHostKeyChecking no\n\tPort 2223\n\n" > ~/.ssh/config
          ssh $SSH_USER@$SERVER_ADDR "./deploy_django.sh"
  run_jenkins:
    name: Run Jenkins
    uses: mickeygoussetorg/trigger-jenkins-job@v1
    with:
      jenkins-server: "https://38600.ddns.net:9002"
      jenkins-job: "projet cicl"
      jenkins-username: "paloudi"
      jenkins-pat: ${{ secrets.JENKINS_TOKEN }}
      poll-time: 10
      timeout-value: 600
      verbose: true
